language: cpp

sudo: false

cache:
  directories:
      - $HOME/lib

matrix:
    include:
        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages:
                      - gcc-7
                      - g++-7
                      - libx11-dev
                      - libgl1-mesa-dev
                      - xorg-dev
                      - libglu1-mesa-dev
                      - libglew-dev
                      - libopenal-dev
                      - cmake-data
                      - cmake
          env: COMPILER=g++-7

        - os: linux
          compiler: clang
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-trusty-5.0
                  packages:
                      - clang-5.0
                      - libx11-dev
                      - libgl1-mesa-dev
                      - xorg-dev
                      - libglu1-mesa-dev
                      - libglew-dev
                      - libopenal-dev
                      - cmake-data
                      - cmake
          env: COMPILER=clang++-5.0

before_install:
    - git submodule update --init
    - export CXX="$COMPILER"
    - ${CXX} --version
    - echo $LANG
    - echo $LC_ALL
    - cmake --version
    - ./travis/install_deps.sh
    - export GLFW_ROOT_DIR=$HOME/lib/$COMPILER/glfw-lib
    - export GLM_ROOT_DIR=$HOME/lib/$COMPILER/glm
    - export GTEST_ROOT=$HOME/lib/$COMPILER/googletest-release-1.7.0

install:

before_script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - cd bin
    - ./unit_test
    - cd ..
    - make package

notifications:
    irc:
        channels:
            - "chat.freenode.net#trillek"
        on_success: change
        on_failure: always
