language: cpp

os: linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - libx11-dev
            - libgl1-mesa-dev
            - xorg-dev
            - libglu1-mesa-dev
            - libglew-dev
            - libopenal-dev
            # - libgtest-dev

compiler:
    - gcc

before_install:
    - echo $LANG
    - echo $LC_ALL
    - set OLD_PWD=$PWD
    # Install CMake 3.1
    - (cd /tmp && wget http://www.cmake.org/files/v3.1/cmake-3.1.3.tar.gz && tar zxf cmake-3.1.3.tar.gz)
    - (cd /tmp/cmake-3.1.3 && cmake . && make && sudo make install) > /dev/null 2>&1
    - cmake --version
    # No ppa for GLFW3 at this time. Compiling by hand!
    - git clone --depth=100 https://github.com/glfw/glfw.git
    - cd glfw
    - CMAKE_CXX_FLAGS=-fPIC CMAKE_C_FLAGS=-fPIC cmake -DCMAKE_INSTALL_PREFIX=$HOME/glfw-lib -DBUILD_SHARED_LIBS:bool=true . && make && make install
    - export GLFW_ROOT_DIR=$HOME/glfw-lib
    - ls $GLFW_ROOT_DIR/
    - cd ..
    # Download GLM 9.5 from github
    - wget https://github.com/g-truc/glm/archive/0.9.5.3.zip
    - unzip 0.9.5.3.zip -d $HOME/glm
    - export GLM_ROOT_DIR=$HOME/glm
    # Download GTest
    - wget http://googletest.googlecode.com/files/gtest-1.7.0.zip
    - unzip gtest-1.7.0.zip -D $HOME/gtest
    - cd $HOME/gtest
    - cmake . && make
    - export GTEST_ROOT=$HOME/gtest
    - cd $OLD_PWD

install:
    # Enforces GCC 4.8
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    # Enforces CLang 3.7
    #- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
  - cd bin
  - ./unit_test
  - cd ..
  - make package

notifications:
    email:
      - luis.panadero@gmail.com
    irc:
        channels:
          - "chat.freenode.net#trillek"
    #      - "chat.freenode.net#project-trillek"
        on_success: change
        on_failure: always
