language: cpp
compiler: gcc
before_install:
    # Grabs a modern version of cmake
    - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install cmake
    # libstdc++-4.8-dev
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    # clang++-3.2 and gcc 4.8
    - sudo add-apt-repository --yes ppa:h-rayflood/llvm
    - sudo apt-get -qq update
    # No ppa for GLFW3 at this time. Compiling by hand!
    - sudo apt-get -qq install xorg-dev libglu1-mesa-dev
    - git clone --depth=100 https://github.com/glfw/glfw.git
    - cd glfw
    - CMAKE_CXX_FLAGS=-fPIC CMAKE_C_FLAGS=-fPIC cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:bool=true .
    - sudo make install
    - cd ..
    # Download GLM 9.5 from github
    - wget https://github.com/g-truc/glm/archive/0.9.5.3.zip
    - unzip 0.9.5.3.zip -d /tmp
    - sudo cp -r /tmp/glm-0.9.5.3/glm /usr/include
install:
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
# GLEW
    - sudo apt-get -q -y install libglew-dev
# GTest
    - sudo apt-get -q -y install libgtest-dev
    - BUILD_PATH=$(pwd)
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - GTEST_ROOT=/usr/src/gtest
    - export GTEST_ROOT
    - cd $BUILD_PATH
#    - sudo apt-get -y install automake libtool cmake
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
script:
  - make
  - cd bin
  - ./unit_test
  - cd ..
  - make package

notifications:
    email:
      - luis.panadero@gmail.com
    irc:
      - "chat.freenode.net#project-trillek"
      - "chat.freenode.net#trillek"
