language: cpp

sudo: false

cache:
  directories:
      - $HOME/cmake
      - $HOME/lib

matrix:
    include:
        - os: linux
        compiler: gcc
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages:
                  - gcc-4.9
                  - g++-4.9
                    - libx11-dev
                    - libgl1-mesa-dev
                    - xorg-dev
                    - libglu1-mesa-dev
                    - libglew-dev
                    - libopenal-dev
        env: COMPILER=g++-4.9

        - os: linux
        compiler: clang
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-precise-3.7
                packages:
                    - clang-3.7
                    - libx11-dev
                    - libgl1-mesa-dev
                    - xorg-dev
                    - libglu1-mesa-dev
                    - libglew-dev
                    - libopenal-dev
        env: COMPILER=clang++-3.7

before_install:
    - git submodule update --init
    - export CXX="$COMPILER"
    - ${CXX} --version
    - echo $LANG
    - echo $LC_ALL
    # Grabs Cmake 3.2
    - ./travis/install_cmake.sh
    - ls -lha $HOME/cmake/
    - export PATH=$HOME/cmake/:$HOME/cmake/bin/:$PATH
    - cmake --version
    - ./travis/install_deps.sh
    - export GLFW_ROOT_DIR=$HOME/lib/$COMPILER/glfw-lib
    - export GLM_ROOT_DIR=$HOME/lib/$COMPILER/glm
    - export GTEST_ROOT=$HOME/lib/$COMPILER/gtest-1.7.0

install:

before_script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - cd bin
    - ./unit_test
    - cd ..
    - make package

notifications:
    #    email:
    #    - luis.panadero@gmail.com
    irc:
        channels:
            - "chat.freenode.net#trillek"
              #      - "chat.freenode.net#project-trillek"
        on_success: change
        on_failure: always
