language: cpp

os: linux

sudo: false
cache:
  directories:
      - $HOME/cmake
      - $HOME/glfw-lib
      - $HOME/glm
      - $HOME/gtest-1.7.0

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - libx11-dev
            - libgl1-mesa-dev
            - xorg-dev
            - libglu1-mesa-dev
            - libglew-dev
            - libopenal-dev

compiler:
    - gcc

before_install:
    # Enforces GCC 4.8
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    # Enforces CLang 3.7
    #- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi
    - echo $LANG
    - echo $LC_ALL
    - ./travis/install_cmake.sh
    - ls -lha $HOME/cmake/
    - export PATH=$HOME/cmake/:$HOME/cmake/bin/:$PATH
    - cmake --version
    - ./travis/install_deps.sh
    - export GLFW_ROOT_DIR=$HOME/glfw-lib
    - export GLM_ROOT_DIR=$HOME/glm
    - export GTEST_ROOT=$HOME/gtest-1.7.0

install:

before_script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - cd bin
    - ./unit_test
    - cd ..
    - make package

notifications:
    email:
        - luis.panadero@gmail.com
    irc:
        channels:
            - "chat.freenode.net#trillek"
              #      - "chat.freenode.net#project-trillek"
        on_success: change
        on_failure: always
